# Generated by Django 3.2.9 on 2021-12-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to='my', verbose_name='图片'),
        ),
    ]
